### ISSUE TITLE
城市选择来回切换一阵，就会报错，不知道从何查起，全是指向的内部错误

### ISSUE THREAD

**Issue by TangStudio** [zhujiang521/PlayWeather#4]
城市选择来回切换一阵，就会报错，不知道从何查起，全是指向的内部错误
java.lang.IllegalStateException: Check failed.
        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$precompose$1.dispose(SubcomposeLayout.kt:566)
        at androidx.compose.foundation.lazy.layout.LazyLayoutPrefetcher.cancelScheduledPrefetch(LazyLayoutPrefetcher.android.kt:274)
        at androidx.compose.foundation.lazy.layout.LazyLayoutPrefetchPolicy.cancelScheduledPrefetch(LazyLayoutPrefetchPolicy.kt:42)
        at androidx.compose.foundation.lazy.LazyListState.notifyPrefetch(LazyListState.kt:305)
        at androidx.compose.foundation.lazy.LazyListState.onScroll$foundation_release(LazyListState.kt:266)
        at androidx.compose.foundation.lazy.LazyListState$scrollableState$1.invoke(LazyListState.kt:150)
        at androidx.compose.foundation.lazy.LazyListState$scrollableState$1.invoke(LazyListState.kt:150)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scrollScope$1.scrollBy(ScrollableState.kt:134)
        at androidx.compose.foundation.gestures.ScrollingLogic.dispatchScroll-f0eR0lY(Scrollable.kt:314)
        at androidx.compose.foundation.gestures.ScrollDraggableState.dragBy-Uv8p0NA(Scrollable.kt:389)
        at androidx.compose.foundation.gestures.DraggableKt$draggable$9$2$2.invokeSuspend(Draggable.kt:244)
        at androidx.compose.foundation.gestures.DraggableKt$draggable$9$2$2.invoke(Unknown Source:8)
        at androidx.compose.foundation.gestures.DraggableKt$draggable$9$2$2.invoke(Unknown Source:4)
        at androidx.compose.foundation.gestures.ScrollDraggableState$drag$2.invokeSuspend(Scrollable.kt:400)
        at androidx.compose.foundation.gestures.ScrollDraggableState$drag$2.invoke(Unknown Source:8)
        at androidx.compose.foundation.gestures.ScrollDraggableState$drag$2.invoke(Unknown Source:4)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invokeSuspend(ScrollableState.kt:148)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invoke(Unknown Source:8)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invoke(Unknown Source:4)
        at androidx.compose.foundation.MutatorMutex$mutateWith$2.invokeSuspend(MutatorMutex.kt:160)
        at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke(Unknown Source:8)
        at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
        at androidx.compose.foundation.MutatorMutex.mutateWith(MutatorMutex.kt:153)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invokeSuspend(ScrollableState.kt:145)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invoke(Unknown Source:8)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
        at androidx.compose.foundation.gestures.DefaultScrollableState.scroll(ScrollableState.kt:144)
        at androidx.compose.foundation.lazy.LazyListState.scroll(LazyListState.kt:235)
        at androidx.compose.foundation.gestures.ScrollDraggableState.drag(Scrollable.kt:398)
        at androidx.compose.foundation.gestures.DraggableKt$draggable$9$2.invokeSuspend(Draggable.kt:241)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:68)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1496)
2022-03-11 09:56:50.746 3806-3806/com.zj.weather E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:1295)
        at android.view.Choreographer.doFrame(Choreographer.java:1022)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1483)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:257)
        at android.app.ActivityThread.main(ActivityThread.java:8307)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by TangStudio** [comment]
已经解决了，升级compose到最新的就解决了
