### ISSUE TITLE
说实话这个天气工程一直崩，我已经改了几处空指针了，还依然闪退。问题还是很多的。

### ISSUE THREAD

**Issue by Pangu-Immortal** [zhujiang521/PlayWeather#6]
说实话这个天气工程一直崩，我已经改了几处空指针了，还依然闪退。问题还是很多的。望修复。

**Comment by zhujiang521** [comment]
嗯嗯，你可以将修改的提上来，没问题的话我将代码合入进去

**Comment by rivenlee0** [comment]
FATAL EXCEPTION: main
                                                                                                    Process: com.zj.weather, PID: 26760
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:557)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
                                                                                                    Caused by: java.io.IOException: NetRes:null
                                                                                                    	at android.location.Geocoder.getFromLocation(Geocoder.java:136)
                                                                                                    	at androidx.glance.appwidget.protobuf.f0.Y0(SourceFile:72)
                                                                                                    	at V2.b.onLocationChanged(SourceFile:20)
                                                                                                    	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:292)
                                                                                                    	at android.location.LocationManager$ListenerTransport.-wrap0(Unknown Source:0)
                                                                                                    	at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java:244)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:176)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6662)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 



--------------------------------------------
LocationManager系统底层报错， 
手机型号：小米MI Play
MIUI版本：MIUI10 9.9.2开发版
OS版本： Android 8.1.0
直接安装release/app-release.apk。
@zhujiang521 大佬帮忙定位一下，
